EcK = 4
EcP = 2
BlockSize = "1MiB"
BlockNum = 20484
SsdBlockCapacity = 9600
TestNum = 80_000
SliceSize = "4KiB"
OutDirPath = "./out/"

[Standalone]
SsdDevPath = "./var/standalone/ssd_dev"
BlobDevPath = "./var/standalone/blob_dev"

[Cluster]
RedisUrl = "redis://127.0.0.1"
WorkerNum = 6
Workers = [
    { SsdDevPath = "./var/cluster/worker-1/ssd_dev", BlobDevPath = "./var/cluster/worker-1/blob_dev" },
    { SsdDevPath = "./var/cluster/worker-2/ssd_dev", BlobDevPath = "./var/cluster/worker-2/blob_dev" },
    { SsdDevPath = "./var/cluster/worker-3/ssd_dev", BlobDevPath = "./var/cluster/worker-3/blob_dev" },
    { SsdDevPath = "./var/cluster/worker-4/ssd_dev", BlobDevPath = "./var/cluster/worker-4/blob_dev" },
    { SsdDevPath = "./var/cluster/worker-5/ssd_dev", BlobDevPath = "./var/cluster/worker-5/blob_dev" },
    { SsdDevPath = "./var/cluster/worker-6/ssd_dev", BlobDevPath = "./var/cluster/worker-6/blob_dev" },
]
