EcK = 4
EcP = 2
BlockSize = "1MiB"
BlockNum = 20484
SsdBlockCapacity = 9600
TestNum = 80_000
SliceSize = "4KiB"
OutDirPath = "./out/"

[Standalone]
SsdDevPath = "./var/standalone/ssd_dev"
HddDevPath = "./var/standalone/hdd_dev"

[Cluster]
RedisUrl = "redis://127.0.0.1"
WorkerNum = 3
Workers = [
    { SsdDevPath = "./var/cluster/worker-1/ssd_dev", HddDevPath = "./var/cluster/worker-1/hdd_dev" },
    { SsdDevPath = "./var/cluster/worker-2/ssd_dev", HddDevPath = "./var/cluster/worker-2/hdd_dev" },
    { SsdDevPath = "./var/cluster/worker-3/ssd_dev", HddDevPath = "./var/cluster/worker-3/hdd_dev" },
    { SsdDevPath = "./var/cluster/worker-4/ssd_dev", HddDevPath = "./var/cluster/worker-4/hdd_dev" },
    { SsdDevPath = "./var/cluster/worker-5/ssd_dev", HddDevPath = "./var/cluster/worker-5/hdd_dev" },
    { SsdDevPath = "./var/cluster/worker-6/ssd_dev", HddDevPath = "./var/cluster/worker-6/hdd_dev" },
]
